using System;
using System.Linq;
using AutomaticInterface;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Tests;

public partial class AccessibilityTests
{
    private static string GenerateCode(string code)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(code);
        var references = AppDomain
            .CurrentDomain.GetAssemblies()
            .Where(assembly => !assembly.IsDynamic)
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>();

        var compilation = CSharpCompilation.Create(
            "SourceGeneratorTests",
            new[] { syntaxTree },
            references,
            new(OutputKind.DynamicallyLinkedLibrary)
        );

        var generator = new AutomaticInterfaceGenerator();

        CSharpGeneratorDriver
            .Create(generator)
            .RunGeneratorsAndUpdateCompilation(
                compilation,
                out var outputCompilation,
                out var diagnostics
            );

        diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();

        return outputCompilation.SyntaxTrees.Skip(1).LastOrDefault()?.ToString();
    }

    [Fact]
    public void AddsPublicMethodToInterface()
    {
        const string code = """

            using AutomaticInterfaceAttribute;
            using System.IO;

            namespace AutomaticInterfaceExample
            {

                [GenerateAutomaticInterface]
                public class DemoClass
                {
                              
                    public string Hello(){return "";}
                }
            }

            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            using System.CodeDom.Compiler;
            using AutomaticInterfaceAttribute;
            using System.IO;

            namespace AutomaticInterfaceExample
            {
                [GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc />
                    string Hello();
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void IgnoresNotPublicMethodToInterface()
    {
        const string code = """

            using AutomaticInterfaceAttribute;
            using System.IO;

            namespace AutomaticInterfaceExample
            {

                [GenerateAutomaticInterface]
                public class DemoClass
                {
                    private string Hello(string x, int y, double z){return x;}
                    internal string Hello2(string x, int y, double z){return x;}
                }
            }

            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            using System.CodeDom.Compiler;
            using AutomaticInterfaceAttribute;
            using System.IO;

            namespace AutomaticInterfaceExample
            {
                [GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithInternal()
    {
        const string code = """

            using AutomaticInterfaceAttribute;
            using System.Threading.Tasks;

            namespace AutomaticInterfaceExample;

            [GenerateAutomaticInterface]
            internal class InternalClass
            {
                public int AProperty { get; set; }
            }

            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            using System.CodeDom.Compiler;
            using AutomaticInterfaceAttribute;
            using System.Threading.Tasks;

            namespace AutomaticInterfaceExample
            {
                [GeneratedCode("AutomaticInterface", "")]
                internal partial interface IInternalClass
                {
                    /// <inheritdoc />
                    int AProperty { get; set; }
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }
    
    [Fact]
    public void WorksWithDefaultAccessModifier()
    {
        const string code = """

                            using AutomaticInterfaceAttribute;
                            using System.Threading.Tasks;

                            namespace AutomaticInterfaceExample;

                            [GenerateAutomaticInterface]
                            class InternalClass
                            {
                                public int AProperty { get; set; }
                            }

                            """;

        const string expected = """
                                //--------------------------------------------------------------------------------------------------
                                // <auto-generated>
                                //     This code was generated by a tool.
                                //
                                //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                                // </auto-generated>
                                //--------------------------------------------------------------------------------------------------

                                using System.CodeDom.Compiler;
                                using AutomaticInterfaceAttribute;
                                using System.Threading.Tasks;

                                namespace AutomaticInterfaceExample
                                {
                                    [GeneratedCode("AutomaticInterface", "")]
                                    internal partial interface IInternalClass
                                    {
                                        /// <inheritdoc />
                                        int AProperty { get; set; }
                                        
                                    }
                                }

                                """;
        GenerateCode(code).Should().Be(expected);
    }
}
