using FluentAssertions;
using Xunit;

namespace Tests;

public partial class GeneratorTests
{
    [Fact]
    public void WorksWithFileScopedNamespace()
    {
        const string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            [GenerateAutomaticInterface]
            class DemoClass
            {
                public string Hello { get; set; }
            }
            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.Hello" />
                    string Hello { get; set; }
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithBracedNamespace()
    {
        const string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample
            {

                [GenerateAutomaticInterface]
                class DemoClass
                {
                    public string Hello { get; set; }
                }
            }
            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.Hello" />
                    string Hello { get; set; }
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithUsingAliases()
    {
        const string code = """

            using AutomaticInterface;
            using TaskAlias = System.Threading.Tasks.Task;

            namespace AutomaticInterfaceExample;

            [GenerateAutomaticInterface]
            class DemoClass
            {
                public TaskAlias Hello { get; set; }
            }


            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.Hello" />
                    global::System.Threading.Tasks.Task Hello { get; set; }
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithIdenticalTypeNames()
    {
        const string code = """

            using AutomaticInterface;
            namespace AutomaticInterfaceExample
            {
                namespace Models1 {
                    public class Model;
                }

                namespace Models2 {
                    public class Model;
                }

                [GenerateAutomaticInterface]
                public class ModelManager
                {
                    public Models1.Model GetModel1() => null!;
                    public Models2.Model GetModel2() => null!;
                }
            }
            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IModelManager
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.ModelManager.GetModel1()" />
                    global::AutomaticInterfaceExample.Models1.Model GetModel1();
                    
                    /// <inheritdoc cref="AutomaticInterfaceExample.ModelManager.GetModel2()" />
                    global::AutomaticInterfaceExample.Models2.Model GetModel2();
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithNestedUsings()
    {
        const string code = """

            using AutomaticInterface;
            namespace RootNamespace
            {
                namespace Models
                {
                    public class Model;
                }

                namespace ModelManager
                {
                    using Models;

                    [GenerateAutomaticInterface]
                    public class ModelManager
                    {
                        public Model GetModel() => null!;
                    }
                }
            }
            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace RootNamespace.ModelManager
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IModelManager
                {
                    /// <inheritdoc cref="RootNamespace.ModelManager.ModelManager.GetModel()" />
                    global::RootNamespace.Models.Model GetModel();
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithShadowedGlobalNamespace()
    {
        const string code = """
            using AutomaticInterface;
            using Task = System.Threading.Tasks.Task;

            namespace AutomaticInterfaceExample
            {
                namespace System.Threading.Tasks
                {
                    public class Task;
                }

                [GenerateAutomaticInterface]
                public class DemoClass
                {
                    public Task GetTask() => null!;
                }
            }
            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.GetTask()" />
                    global::System.Threading.Tasks.Task GetTask();
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithGlobalUsing()
    {
        const string code = """
            global using GlobalNamespace;
            using AutomaticInterface;

            namespace GlobalNamespace
            {
                public class AClass;
            }

            namespace AutomaticInterfaceExample
            {
                [GenerateAutomaticInterface]
                public class DemoClass
                {
                    public AClass GetClass() => null!;
                }
            }
            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.GetClass()" />
                    global::GlobalNamespace.AClass GetClass();
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }
}
