using FluentAssertions;
using Xunit;

namespace Tests;

public partial class GeneratorTests
{
    [Fact]
    public void WorksWithMethodOutParameter()
    {
        const string code = """

            using AutomaticInterface;
            using System.Threading.Tasks;

            namespace AutomaticInterfaceExample;
            [GenerateAutomaticInterface]
            public class DemoClass
            {
                public void AMethod(out int someOutParameter)
                {
                    someOutParameter = 1;
                }
            }

            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.AMethod(out int)" />
                    void AMethod(out int someOutParameter);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithMethodInParameter()
    {
        const string code = """

            using AutomaticInterface;
            using System.Threading.Tasks;

            namespace AutomaticInterfaceExample;
            [GenerateAutomaticInterface]
            public class DemoClass
            {
                public void AMethod(in int someOutParameter)
                {
                }
            }

            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.AMethod(in int)" />
                    void AMethod(in int someOutParameter);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithMethodRefParameter()
    {
        const string code = """

            using AutomaticInterface;
            using System.Threading.Tasks;

            namespace AutomaticInterfaceExample;
            [GenerateAutomaticInterface]
            public class DemoClass
            {
                public void AMethod(ref int someOutParameter)
                {
                }
            }

            """;

        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.AMethod(ref int)" />
                    void AMethod(ref int someOutParameter);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithOptionalParameters()
    {
        const string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public bool TryStartTransaction(
                        string file = "",
                        string member = "",
                        int line = 0,
                        bool notify = true)
                    {
            return true;
            }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.TryStartTransaction(string, string, int, bool)" />
                    bool TryStartTransaction(string file = "", string member = "", int line = 0, bool notify = true);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithParamsParameters()
    {
        const string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                public void AMethod(params int[] numbers)
                {
                }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.AMethod(params int[])" />
                    void AMethod(params int[] numbers);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithOptionalStructParameters()
    {
        const string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            public struct MyStruct
            {
                private int Bar;
            }

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public bool TryStartTransaction(MyStruct data = default(MyStruct))
                    {
            return true;
            }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.TryStartTransaction(AutomaticInterfaceExample.MyStruct)" />
                    bool TryStartTransaction(global::AutomaticInterfaceExample.MyStruct data = default(global::AutomaticInterfaceExample.MyStruct));
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithOptionalNullParameters()
    {
        const string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public bool TryStartTransaction(string data = null)
                    {
            return true;
            }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.TryStartTransaction(string)" />
                    bool TryStartTransaction(string data = null);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithOptionalEnumParameters()
    {
        string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            public enum Selection {First, Second, Third};

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public string GetSelection(Selection selection = Selection.Second)
                    {
                        return "";
                    }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.GetSelection(AutomaticInterfaceExample.Selection)" />
                    string GetSelection(global::AutomaticInterfaceExample.Selection selection = (global::AutomaticInterfaceExample.Selection)1);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithOptionalZeroEnumParameters()
    {
        string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            public enum Selection {First, Second, Third};

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public string GetSelection(Selection selection = Selection.First)
                    {
                        return "";
                    }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.GetSelection(AutomaticInterfaceExample.Selection)" />
                    string GetSelection(global::AutomaticInterfaceExample.Selection selection = 0);
                    
                }
            }

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithNullableOptionalEnumParameters()
    {
        string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            public enum Selection {First, Second, Third};

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public string GetSelection(Selection? selection = Selection.Second)
                    {
                        return "";
                    }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            #nullable enable
            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.GetSelection(AutomaticInterfaceExample.Selection?)" />
                    string GetSelection(global::AutomaticInterfaceExample.Selection? selection = (global::AutomaticInterfaceExample.Selection)1);
                    
                }
            }
            #nullable restore

            """;
        GenerateCode(code).Should().Be(expected);
    }

    [Fact]
    public void WorksWithNullableOptionalZeroEnumParameters()
    {
        string code = """

            using AutomaticInterface;

            namespace AutomaticInterfaceExample;

            public enum Selection {First, Second, Third};

            [GenerateAutomaticInterface]
            public class DemoClass
            {
                    public string GetSelection(Selection? selection = Selection.First)
                    {
                        return "";
                    }
            }


            """;
        const string expected = """
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------

            #nullable enable
            namespace AutomaticInterfaceExample
            {
                [global::System.CodeDom.Compiler.GeneratedCode("AutomaticInterface", "")]
                public partial interface IDemoClass
                {
                    /// <inheritdoc cref="AutomaticInterfaceExample.DemoClass.GetSelection(AutomaticInterfaceExample.Selection?)" />
                    string GetSelection(global::AutomaticInterfaceExample.Selection? selection = 0);
                    
                }
            }
            #nullable restore

            """;
        GenerateCode(code).Should().Be(expected);
    }
}
